# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      request:
        runs-on: windows-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        ##- name: Set up PowerShell
          ## uses: actions/setup-powershell@v1
    
        - name: Run PowerShell script
          run: |
            powershell -File GetStockPrice.ps1 -apikey ${{secrets.STOCKDATA_API_KEY}}

        - name: Publish stock_price_report
          uses: actions/upload-artifact@v4
          with:
            name: stock_price_report
            path: '**/output/**'
